---
abstract: 'Test your SYNOPSIS code'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Synopsis
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  Test::Builder: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
